name: Run DSE Scraper

on:
  schedule:
    - cron: '0 9 * * *'  # 5PM malay time
  workflow_dispatch:  # ম্যানুয়ালি চালাতে পারবে

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Scraper
        env:
          MONGO_URI: ${{ secrets.MONGO_URI}}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN}}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID}}
        run: node services/dseScraper.js
